### ISSUE TITLE
Ubuntu 18.04 not building

### ISSUE THREAD

**Issue by Bengkel** [RobertoPrevato/AzureDevOps-agents#16]
basic.sh in  ubuntu18.04-base breaks docker build. 

`E: Package 'libicu55' has no installation candidate`

**Comment by RobertoPrevato** [comment]
Hi @Bengkel, sorry for replying late. I didn't notice your message among my notifications.
The base image is building with the GitHub workflow that runs weekly, I don't see the problem with `libicu55`. I came back today to this repo, because the Python image started failing only starting from this weekend.

If you take a look at the [build history](https://github.com/RobertoPrevato/AzureDevOps-agents/actions) and the [logs of the last build](https://github.com/RobertoPrevato/AzureDevOps-agents/runs/1018764026?check_suite_focus=true) (where the Python image is failing), you will see that the base image for Ubuntu 18.04 is working.

Do you know what might be causing the issue with you? Could it have been a transient issue with the public repositories?

**Comment by RobertoPrevato** [comment]
Closing because GitHub workflow builds demonstrate the ubuntu18-04-base image is building (just fixed the Python image at https://github.com/RobertoPrevato/AzureDevOps-agents/commit/0cb81b05464d8adeb0f737b4fc35bca881771249)
